version: "3.9"

networks:
  product-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: product-api:latest
    container_name: product-api
    networks:
      - product-network
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M


  benchmark:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    image: product-benchmark:latest
    container_name: product-benchmark
    networks:
      - product-network
    depends_on:
      - app
    command: sh -c "chmod +x /app/benchmark.sh && /app/benchmark.sh"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M



