spring.application.name=Senior-java-tech-challenge

spring.datasource.url=jdbc:h2:mem:seniorjtechchallenge;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Nivel de log para diagnóstico de caché
logging.level.org.springframework.cache=DEBUG
logging.level.org.demo.seniorjavatechchallenge.application.service.GetCurrentPriceService=INFO
logging.level.org.demo.seniorjavatechchallenge.infrastructure.persistence.repository.PriceJdbcRepository=INFO
